### ISSUE TITLE
Why isn't perspective working from within a vsketch project?

### ISSUE THREAD

**Issue by rothos** [abey79/vpype-perspective#5]
I really want to get this plugin working. I installed it successfully, I think.

If I try using vpype-perspective on the command line, it works:
```
$ vpype pspread --help
Usage: vpype pspread [OPTIONS] DELTAZ

  Set the spread distance.

[...]
```

But when I run the wobbly_cylinders example, it fails:
```
$ vsk run wobbly_cylinders/
Running sketch: [...]/wobbly_cylinders/sketch_wobbly_cylinders.py
Unexpected error when running sketch: No such command 'pspread'.
Traceback (most recent call last):
[...]
click.exceptions.UsageError: No such command 'pspread'.
```

Any idea what's going on here? There are a lot of pieces here I'm not familiar with, so after uninstalling and reinstalling, I'm sort of at a loss. Seems the error originates in a `click` function. Does vsketch's vpype somehow not see the plugins?

I did see a warning that vpype is not yet compatible with Python 3.11... is this the exact thing one would expect to fail with python 3.11? Everything else I've done has worked so far. (Update: I tried it on python 3.10 and got the same error.)

Thanks.

**Comment by rothos** [comment]
Whoops, didn't realize I had to inject plugins to vsketch too. It's working now. Thank you for your work!

https://vsketch.readthedocs.io/en/latest/install.html#installing-plug-ins

**Comment by abey79** [comment]
Correct 👍🏻 

I'll move this issue in the Q&A section.
